### ISSUE TITLE
Unhandled Exception: PlatformException(FWFEvaluateJavaScriptError, Failed evaluating JavaScript., Instance of 'NSError', null) #0      WKWebViewHostApiImpl.evaluateJavaScriptForInstances (package:webview_flutter_wkwebview/src/web_kit/web_kit_api_impls.dart:1010:7) <asynchronous suspension> #1      WebKitWebViewPlatformController.runJavascript (package:webview_flutter_wkwebview/src/web_kit_webview_widget.dart:349:7)

### ISSUE THREAD

**Issue by apps-voizzit** [shah-xad/webview_flutter_plus#39]

**Comment by neeluagrawal04** [comment]
Firebase crashlytics is reporting regressive crash on same. Any solution for this?
Fatal Exception: FlutterError
PlatformException(FWFEvaluateJavaScriptError, Failed evaluating JavaScript., Instance of 'NSError', null). Error thrown null.
Fatal Exception: FlutterError
0  ???                            0x0 WKWebViewHostApiImpl.evaluateJavaScriptForInstances + 1010 (web_kit_api_impls.dart:1010)
1  ???                            0x0 WebKitWebViewPlatformController.runJavascriptReturningResult + 365 (web_kit_webview_widget.dart:365)

**Comment by andrejvujic** [comment]
Same issue when trying to run JavaScript inside web view on iOS.

**Comment by houssam15** [comment]
same here , please solve this problem
