### ISSUE TITLE
WKWebViewHostApiImpl.evaluateJavaScriptForInstances 

### ISSUE THREAD

**Issue by lanyuzx** [shah-xad/webview_flutter_plus#54]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(FWFEvaluateJavaScriptError, Failed evaluating JavaScript., JavaScript execution returned a result of an unsupported type (WKErrorDomain:5:{NSLocalizedDescription: JavaScript execution returned a result of an unsupported type}), null)
#0      WKWebViewHostApiImpl.evaluateJavaScriptForInstances (package:webview_flutter_wkwebview/src/web_kit/web_kit_api_impls.dart:1082:7)
<asynchronous suspension>
#1      WebKitWebViewController.runJavaScriptReturningResult (package:webview_flutter_wkwebview/src/webkit_webview_controller.dart:418:28)
<asynchronous suspension>
#2      WebViewControllerPlus.onLoaded (package:webview_flutter_plus/src/controller.dart:40:12)
<asynchronous suspension>

**Comment by houssam15** [comment]
same problem here i think a permission is needed but i don't found it or ios restrict building apps using webview , because javascript is restricted maybe we set JavaScriptMode to unrestricted , and also same code  work fine in android
